# ── MongoDB ─────────────────────────────────────
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# ── JWT ─────────────────────────────────────────
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-ms=1800000
security.jwt.refresh-expiration-ms=86400000

# ── Sesiones ────────────────────────────────────
security.session.max-inactive-minutes=30
security.session.max-conexiones=3
security.session.max-intentos=5
security.session.bloqueo-minutos=15

# ── POSTGRESQL ───────────────────────────────
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ── Parámetros ──────────────────────────────────
ESTADO_VENTA_DEFAULT=PAGADA

# ── Multipart / File Upload ─────────────────────
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ── Brevo (Email API) ───────────────────────────
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${SPRING_MAIL_USERNAME}
brevo.sender.name=DriveMaster

# ── Gemini ──────────────────────────────────────
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.1-flash-lite
gemini.rate.limit.ms=4000

# ── Cloudinary ──────────────────────────────────
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=drivemaster/productos

# ── Google OAuth2 ───────────────────────────────
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

google.client-id=${GOOGLE_CLIENT_ID}


# ── Wompi metodo de pagos ───────────────────────────────
wompi.public_key=${WOMPI_PUBLIC_KEY:pub_test_EVCqMADK6jSxbH1PX9X2FvROdIECCq2M}
wompi.integrity_key=${WOMPI_INTEGRITY_KEY:test_integrity_idprqtfhGOF0N4NAMafBW1kBBJcNg8oc}
wompi.api_url=${WOMPI_API_URL:https://sandbox.wompi.co/v1}
wompi.checkout_url=https://checkout.wompi.co/p/
wompi.redirect_url=${WOMPI_REDIRECT_URL}


# ── Frontend ────────────────────────────────────
frontend.url=${FRONTEND_URL}