spring.application.name=drivemaster

spring.mongodb.uri=mongodb+srv://brainyblanco17_db_user:Familia@drivemasterdb.zeruvba.mongodb.net/drivemasterDB?retryWrites=true&w=majority

security.jwt.secret=9p6Sx7M2k21Jf7qLdZcWnG8vP0yR4uXt
security.jwt.expiration-ms=1800000
