spring.mongodb.uri=mongodb+srv://brainyblanco17_db_user:Familia@drivemasterdb.zeruvba.mongodb.net/drivemasterDB?retryWrites=true&w=majority
security.jwt.secret=9p6Sx7M2k211f7qLdzcWng8vP0yR4uXt
security.jwt.expiration-ms=1800000
security.jwt.refresh-expiration-ms=86400000

security.session.max-inactive-minutes=30
security.session.max-conexiones=3
security.session.max-intentos=5
security.session.bloqueo-minutos=15

# ── MySQL ──────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/drivemaster_config?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=Familia
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

ESTADO_VENTA_DEFAULT=PAGADA